baseURL = 'https://rico4338.github.io/'
languageCode = 'zh-TW'
title = '理科羊的放牧場'
theme = 'LoveIt'
themesDir = "themes"
googleAnalytics = ""
disqusShortname = "disqus_FlIJJ6A60y"
[author]
  name = "RicoYang"
  email = "dsc4338@hotmail.com.tw"
  link = ""
[params]
  defaultTheme = "dark"

  [params.header]
    [params.header.title]
      logo = "https://s.gravatar.com/avatar/c1d9ab42be6ce5bb2cc021ba34745646?s=80"
      name = "理科羊的放牧場"
      typeit = true
  [params.home]
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = "dsc4338@hotmail.com.tw"
      # URL of avatar shown in home page
      # 主页显示头像的 URL
      avatarURL = "https://s.gravatar.com/avatar/c1d9ab42be6ce5bb2cc021ba34745646?s=80"
      # title shown in home page (HTML format is supported)
      # 主页显示的网站标题 (支持 HTML 格式)
      title = "理科羊的放牧場"
      # subtitle shown in home page (HTML format is supported)
      # 主页显示的网站副标题 (允许 HTML 格式)
      subtitle = "努力學習一直都是成長的最佳捷徑"
      # whether to use typeit animation for subtitle
      # 是否为副标题显示打字机动画
      typeit = true
      # whether to show social links
      # 是否显示社交账号
      social = true
      # disclaimer (HTML format is supported)
      # 免责声明 (支持 HTML 格式)
      disclaimer = ""