name: Greet Everyones
on:
  push:
    branches:
      - source

jobs:
  build:
    name: deploy hugo
    runs-on: ubuntu-latest

    steps:
      - name: checkout and init submodules
        uses: actions/checkout@v3
        with:
          ref: source
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify --gc --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/source'
        with:
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
